📌 Pin to `mongoose` less than v9
v9 has breaking changes that break this library. Let's include this in
our `package.json` so that downstream apps don't try to bump this and
break.

```
TypeError: Cannot destructure property 'instance' of 'this.mongoosePath.caster' as it is undefined.
    at Property.type (file:///Users/alec/git/work/reedsy/reedsy-editor-admin/node_modules/@reedsy/adminjs-mongoose/lib/property.js:95:19)
```